server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: eMSPDemo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
